openapi: "3.0.1"
info:
  title: "getData"
  version: "2022-08-03 03:42:21UTC"
servers:
- url: "https://ke7gmpy835.execute-api.ap-southeast-2.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
paths:
  /myFirstFunction:
    get:
      responses:
        default:
          description: "Default response for GET /myFirstFunction"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:ap-southeast-2:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-southeast-2:931299814805:function:myFirstFunction/invocations"
        connectionType: "INTERNET"
x-amazon-apigateway-importexport-version: "1.0"
